spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

    data: classpath:/data.sql

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    logfile:
      enabled: true
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
  file: .logs/file.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"